title: Hello, world! I'm Feng Zhou
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Feng Zhou # add your name
author-img: feng-zhou.jpeg # add your photo
about-author: I am a system engineering. Always hungry to keep learning. # add description
social-twitter: zhoufwind # add your Twitter handle
social-facebook: zhoufwind # add your Facebook handle
social-github: zhoufwind # add your Github handle
social-linkedin: stephen-zhou-a8999442 # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: zhoufwind # add your discus identifier

# Tracker
analytics: UA-121576238-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
